# Use the VS Code plugin: `REST Client`

@url = http://localhost:7801
@nodeAddr1 = /ip4/8.219.75.114/tcp/6001
@nodeId1 = 16Uiu2HAmS4CErxrmPryJbbEX2HFQbLK8r8xCA5rmzdSU59rHc9AF
@nodeAddr2 = /ip4/122.99.183.54/tcp/6001
@nodeId2 = 16Uiu2HAmRTpigc7jAbsLndB2xDEBMAXLb887SBEFhfdJeEJNtqRM
@nodeAddr3 = /ip4/192.168.1.86/tcp/7001
@nodeId3 = 16Uiu2HAmKk7Fg4WysTpEGd5q1wH2NL4wmxyQ5Nj4HhkQHyB3bDhm
@nodeAddr4 = /ip4/10.0.20.43/tcp/7001
@nodeId4 = 16Uiu2HAmDBYxgdKxeCbmn8hYiqwK3xHR9533WDdEYmpEDQ259GTe

###
# Get the PeerInfo of the node itself

GET {{url}}/api/v0/id HTTP/1.1
Content-Type: application/json

###
# Get peer node list

GET {{url}}/api/v0/peers HTTP/1.1
Content-Type: application/json

###
# Get the PeerInfo of any node
# @prompt node_id The node ID you want to query

POST {{url}}/api/v0/peer HTTP/1.1
Content-Type: application/json

{
  "node_id": "{{nodeId1}}"
}

###
# Use AI model image generation
# @prompt node_id The node ID you want to query
# @prompt model The model you want to use
# @prompt prompt The prompt word parameters passed to the model

POST {{url}}/api/v0/image/gen HTTP/1.1
Content-Type: application/json

{
  "node_id": "{{nodeId1}}",
  "model": "test",
  "prompt": "a bird flying in the sky"
}

###
# Get the host information of any node.

POST {{url}}/api/v0/host/info HTTP/1.1
Content-Type: application/json

{
  "node_id": "{{nodeId1}}"
}

###
# List the peers with which the node has established connections

POST {{url}}/api/v0/swarm/peers
Content-Type: application/json

###
# List all peers known to this node

POST {{url}}/api/v0/swarm/addrs
Content-Type: application/json

###
# Connect to the specified node
# @prompt node_addr The node address you want to connect to

POST {{url}}/api/v0/swarm/connect
Content-Type: application/json

{
  "node_addr": "{{nodeAddr4}}/p2p/{{nodeId4}}"
}

###
# Disconnect from the specified node
# @prompt node_addr The node address you want to disconnect from

POST {{url}}/api/v0/swarm/disconnect
Content-Type: application/json

{
  "node_addr": "{{nodeAddr4}}/p2p/{{nodeId4}}"
}

###
# List the topic subscribers known to this node

POST {{url}}/api/v0/pubsub/peers
Content-Type: application/json
