name: Go Build and Release

on:
  push:
    # branches: [main]
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.6
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build Program linux_amd64
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=${{ github.ref_name }}" -o host_${{ github.ref_name }}_linux_amd64 ./host/main.go
      - name: Build Program linux_arm64
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags "-X main.version=${{ github.ref_name }}" -o host_${{ github.ref_name }}_linux_arm64 ./host/main.go
      - name: Build Program darwin_arm64
        run: |
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -ldflags "-X main.version=${{ github.ref_name }}" -o host_${{ github.ref_name }}_darwin_arm64 ./host/main.go
      - name: Build Program darwin_amd64
        run: |
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.version=${{ github.ref_name }}" -o host_${{ github.ref_name }}_darwin_amd64 ./host/main.go
      - name: Build Program windows_amd64
        run: |
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags "-X main.version=${{ github.ref_name }}" -o host_${{ github.ref_name }}_windows_amd64.exe ./host/main.go
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            host_${{ github.ref_name }}_linux_amd64
            host_${{ github.ref_name }}_linux_arm64
            host_${{ github.ref_name }}_darwin_arm64
            host_${{ github.ref_name }}_darwin_amd64
            host_${{ github.ref_name }}_windows_amd64.exe
